apigateway:
  build: ./api-gateway-service/
  restart: unless-stopped
  ports:
    - "8080:8080"
  environment:
    CRAWLER_SERVICE_HOST: crawlerservice
    CRAWLER_QUEUE_SERVICE_HOST: crawlerqueueservice


crawlerservice:
  build: ./crawler-service/
  restart: unless-stopped
  ports:
    - "8081:8080"

crawlerqueueservice:
  build: ./crawler-queue-service/
  restart: unless-stopped
  ports:
    - "8082:8080"

rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
